<?php

namespace ArticleAdminBundle\Repository;

use ArticleAdminBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyid($id)
    {          $query=$this->getEntityManager()
        ->createQuery("select c from ArticleAdminBundle:Article c where  c.id='$id'");//affiche la liste des objets
        return $query->getResult();
    }
}
