<?php

namespace ArticleAdminBundle\Repository;

use ArticleAdminBundle\Entity\Commentaire;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findComment($id)
    {          $query=$this->getEntityManager()
        ->createQuery("select c from ArticleAdminBundle:Commentaire c where  c.article='$id'");//affiche la liste des objets
        return $query->getResult();
    }

    public function mysearch($input){
        $query=$this->getEntityManager()
            ->createQuery(" select c.id,c.contenue, c.dateComt, c.likes,a.titre,u.username from ArticleAdminBundle\Entity\Commentaire c left join ArticleAdminBundle\Entity\Article a with c.article=a.id left join AppBundle\Entity\User u with c.user=u.id where c.contenue like :key or c.dateComt like :key or a.titre like :key or u.username like :key")
            ->setParameter("key","%".$input."%");
        return $query->getArrayResult();
    }

}