<?php

namespace ArticleAdminBundle\Repository;

/**
 * FavorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findfav($user)
    {   $query=$this->getEntityManager()
        ->createQuery("select c from ArticleAdminBundle:Favorie c where  c.user='$user'");//affiche la liste des objets
        return $query->getResult();
    }
    public function favarticle()
    {   $query=$this->getEntityManager()
        ->createQuery("select c from ArticleAdminBundle:Favorie c ORDER BY c.dateAjout DESC ");
        $query->setMaxResults(2);
    }
}
