article_user:
    resource: "@ArticleUserBundle/Resources/config/routing.yml"
    prefix:   /ArticleUser

article_admin:
    resource: "@ArticleAdminBundle/Resources/config/routing.yml"
    prefix:   /ArticleAdmin


app:
    resource: '@AppBundle/Controller/'
    type: annotation
