commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

