<?php

namespace CommandeBundle\Repository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastAdresse(){
        $query=$this->getEntityManager()->createQuery("select  a from CommandeBundle:adresse a where a.id = (select max(b.id) from CommandeBundle:adresse b)");
        return $query->getResult();
    }
}
