<?php

namespace CommandeBundle\Repository;

/**
 * PenaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PenaliteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPenalite()
    {
        $query=$this->getEntityManager()->createQuery("select a from CommandeBundle:Penalite a");

        return $query->getResult();
    }
}
