<?php

namespace StockAdminBundle\Repository;

/**
 * AccessoiresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoiresRepository extends \Doctrine\ORM\EntityRepository
{
}
