<?php

namespace StockAdminBundle\Repository;

/**
 * OffreARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreARepository extends \Doctrine\ORM\EntityRepository
{public function existA($input){

    $query=$this->getEntityManager()->createQuery("SELECT c FROM StockAdminBundle:OffreA c where c.accesoires=$input");
    return $query->getResult();
}public function getallusers(){

    $query=$this->getEntityManager()->createQuery("SELECT c FROM AppBundle:User");
    return $query->getResult();}}
