<?php

namespace StockAdminBundle\Repository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    public function exist($input){

    $query=$this->getEntityManager()->createQuery("SELECT c FROM StockAdminBundle:Offre c where c.velo=$input");
    return $query->getResult();
}

    public function getallusers(){

        $query=$this->getEntityManager()->createQuery("SELECT c FROM AppBundle:User");
        return $query->getResult();
    }
}
