<?php

namespace StockAdminBundle\Repository;

/**
 * VeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloRepository extends \Doctrine\ORM\EntityRepository
{public function findASC(){
    $qb = $this->createQueryBuilder('p')
        ->orderBy('p.prixAchat', 'ASC');
    $query = $qb->getQuery();

    return $query->execute();
}

    public function findDESC(){
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.prixAchat', 'DESC');
        $query = $qb->getQuery();

        return $query->execute();
    }
}
